### ISSUE TITLE
Submit the plugin to Packagist

### ISSUE THREAD

**Issue by juho-jaakkola** [Daltonmedia/elgg_cookieconsent#1]
Submit the plugin to: https://packagist.org/ so it will become publicly available as a composer package.

Also set up an auto-update hook to Github, so also future releases will get added automatically to Packagist. (Packagist should give you instructions how to do it.)

**Comment by juho-jaakkola** [comment]
Bump

**Comment by Daltonstudio** [comment]
Done, sorry, totally forgot about it. 
https://packagist.org/packages/daltonmedia/elgg_cookieconsent
